config/routes.rb
Weixin::Application.routes.draw do
  resources :mains
  resources :cccabouts do
    collection do
      get 'disclaimer'
      get 'privacy'
      get 'job'
      get 'contact'
      get 'links'
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  root :to => "main#index"
  resources :mains
  resources :services do
    collection do
      get 'website'
      get 'marketing'
    end
  end
  resources :abouts
  resources :cases
  resources :contact
  resources :questions
  resources :weixin do
    collection do
      get 'contrast'
    end
  end
  resources :news
  namespace :admin do
    match '' => 'cases#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end
    resources :cases
    resources :questions
    resources :journalisms
    resources :jobs
    resources :cccshs
  end

end

app/models/case.rb
class Case < ActiveRecord::Base
  validates :title, :presence => {:message => "案例标题不能为空！"}, :length => {:maximum => 15, :message => "题目长度不能超过15"}
  validates :content, :presence => {:message => "案例内容不能为空！"}, :length => {:maximum => 200, :message => "案例内容长度不能超过200"}

  attr_accessor :avatar
  has_attached_file :avatar, :styles => {:zhengchang => "350x210>", :thumb => "70x42>", :anli => "480x800>"}, :default_url => "/images/:style/missing.png",
                    :url => "/case/:id_partition/:style/:filename"
  validates_attachment_size :avatar, :less_than => 2.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/png', 'image/x-png', 'image/jpeg', 'image/pjpeg', 'image/jpg']

  scope :order_ct_desc, lambda { order("created_at DESC") }

  @filepath="public/cases/"
  @previewpath = "previews/"

  # 删除图片
  def self.deletefile(r_id)
    idstr = format("%09d", r_id.to_s)
    one_path = @filepath+idstr[0, 3]+"/"
    two_path = one_path + idstr[3, 3]+"/"
    three_path = two_path + idstr[6, 3]+"/"
    begin
      `rm -rf #{Rails.root+three_path}`
    rescue
      if system "rm -rf #{Rails.root+three_path}"
        return true
      else
        return false
      end
    end
    return true
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/journalism.rb
class Journalism < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/main.rb
class Main < ActiveRecord::Base

  validates :name, :presence => {:message => "姓名不能为空！"}
  validates :tel, :presence => {:message => "电话不能为空！"}
  validates :address, :presence => {:message => "地址不能为空！"}
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/zhaoshang.rb
class Zhaoshang < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def index
    @roll = Case.all.order_ct_desc.page(params[:page]).per(30)
  end

  def show
    @roll = Case.find params[:id]
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @questions = Question.order_ct_desc.page(params[:page]).per(3)
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
    @roll = Case.all.order_ct_desc.page(params[:page]).per(16)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @roll = Case.all.order_ct_desc.page(params[:page]).per(10)
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
  end

  def show
    @journalism = Journalism.find params[:id]
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_datetime_format(datetime)
    datetime.strftime(" %Y年%m月%d日 %H:%M:%S")
  end

  def my_time_format(datetime)
    datetime.strftime(" %Y-%m-%d")
  end

  def truncate_u(text, length = 30, truncate_string = "...")
    l=0
    char_array=text.unpack("U*")
    char_array.each_with_index do |c, i|
      l = l+ (c<127 ? 0.5 : 1)
      if l>=length
        return char_array[0..i].pack("U*")+(i<char_array.length-1 ? truncate_string : "")
      end
    end
    return text
  end

  def my_datetime(datetime)
    datetime.strftime(" %Y.%m.%d")
  end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/cccabouts_helper.rb
module CccaboutsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/weixin_helper.rb
module WeixinHelper
end

app/views/comment/_cccdaohang.html.erb
<div id="header">
  <h1><a class="logo" title="logo" href="http://www.zhenbaren.com/">Logo</a></h1>

  <div id="topright">
    <ul id="nav" class="clearfix">
      <li><a title="长春车生活" href="http://www.changchunche.com/">长春车生活官网</a></li>
      <li><a title="长春车生活论坛" href="http://bbs.changchunche.com/">长春车生活论坛</a></li>

      <li>
        <a class="header-new" title="商户联盟" href="http://www.zhenbaren.com/" target="_blank">商户联盟
          <img src="/images/cccshabout/new_3.gif" width="11" height="12">
        </a>
      </li>
      <li><a title="使用帮助" href="http://bbs.changchunche.com/misc.php?mod=faq">使用帮助</a></li>
      <li><a title="长春车生活官方" href="http://www.changchunche.com/" target="_blank">技术支持</a></li>
    </ul>
  </div>
  <div class="clear"></div>
</div>

app/views/comment/_cchome.html.erb
<div id="sidebar">
  <ul>
    <li class="focus"><a class="hover" href="/cccabouts">关于我们</a></li>
    <li><a href="<%= disclaimer_cccabouts_path %>">免责声明</a></li>
    <li><a href="<%= privacy_cccabouts_path %>">隐私条款</a></li>
    <li><a href="<%= job_cccabouts_path %>">工作机会</a></li>
    <li><a href="<%= contact_cccabouts_path %>">联系我们</a></li>
    <li><a href="<%= links_cccabouts_path %>">业务合作</a></li>
    <li><a href="http://j.map.baidu.com/7GRWv" target="_blank">网站地图</a></li>
    <li><a href="http://bbs.changchunche.com/misc.php?mod=faq" target="_blank">帮助中心</a></li>
  </ul>
  <dl class="other-help">
    <dt class="icon_phone">客服电话：</dt>
    <dd>15104419753</dd>
    <dt class="icon_forum">公司地址：</dt>
    <dd>长春市解放大路财富广场</dd>
  </dl>
</div>

app/views/comment/_footer.html.erb
<footer>
  <div id="footerinfo">
    <div class="wrapper">
      <div class="adrtel">
        <a href="#" class="tel">咨询电话：4008-455-789 </a>办公地址：长春市南关区解放大路与平阳街交汇<a href="http://j.map.baidu.com/AZsfr">【地图查询】</a>
      </div>
      <p>Copyright &#169; 2011-2014 www.pxwgj.com .All Rights Reserved. 朋兴微管家 版权所有.
        <a href="http://www.ccpxcm.com/" title="朋兴文化传媒有限公司" target="_blank">朋兴文化传媒有限公司</a>
        <a href="http://www.ccpxcm.com/ours/elite_team" title="朋兴做网站" target="_blank"> 朋兴专业团队 </a>
        <a href="http://www.pxwgj.com/services/marketing/" title="朋兴网站推广" target="_blank">朋兴网站推广</a>
        <script language="javascript" type="text/javascript" src="../javascripts/4713898.js"></script>
      </p>

      <img src="../images/foot_map.png" id="homemap" alt="长春朋兴文化传媒有限公司地理位置" height="156" width="208">

      <div class="links">
        <p> 友情链接：</p>
        <li><a href="http://www.ccpxcm.com/" target="_blank">长春朋兴文化传媒有限公司</a></li>
        <li><a href="http://www.xinxiaowei.cn/" target="_blank">新校尉美术艺术培训基地</a></li>
        <em>
          朋兴-<a href="http://www.pxwgj.com/" target="_blank" title="朋兴网站建设">网站建设</a>
          高端品牌！ 三年<a href="http://www.pxwgj.com/" target="_blank" title="朋兴网站建设公司">朋兴网站建设公司</a>
          运营经验、企业<a href="http://www.pxwgj.com/" title="品牌网站建设">品牌网站建设</a>
          经验；欢迎<a href="http://www.pxwgj.com/" title="网站建设">网站建设公司</a>
        </em>

        <p></p>
      </div>
    </div>
  </div>
</footer>
<div id="service2">
  <%= render "comment/kefu" %>
</div>

<!-- /footer -->
<script type="text/javascript" src="../javascripts/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="../javascripts/jquery.plugin.min.js"></script>
<!--[if IE 6]>
<script type="text/javascript" src="../javascripts/killie6.js"></script>
<![endif]-->
<script type="text/javascript">
    //<![CDATA[
    <!--首页 -->
    $('.ad_img,#banner_ctr,.logo').pngFix();
    //Banner Start
    var curIndex = 0;
    var time = 800;
    var slideTime = 5000;
    var adTxt = $("#banner_img>li>div>.ad_txt");
    var adImg = $("#banner_img>li>div>.ad_img");
    var int = setInterval("autoSlide()", slideTime);

    $("#banner_ctr>ul>li[class!='first-item'][class!='last-item']").click(function () {
        show($(this).index("#banner_ctr>ul>li[class!='first-item'][class!='last-item']"));
        window.clearInterval(int);
        int = setInterval("autoSlide()", slideTime);
    });

    function autoSlide() {
        curIndex + 1 >= $("#banner_img>li").size() ? curIndex = -1 : false;
        show(curIndex + 1);
    }
    function show(index) {
        $.easing.def = "easeOutQuad";
        $("#drag_ctr,#drag_arrow").stop(false, true).animate({left: index * 24 + 6}, 300);
        $("#banner_img>li").eq(curIndex).stop(false, true).fadeOut(time);
        adTxt.eq(curIndex).stop(false, true).animate({top: "340px"}, time);
        adImg.eq(curIndex).stop(false, true).animate({right: "120px"}, time);
        setTimeout(function () {
            $("#banner_img>li").eq(index).stop(false, true).fadeIn(time);
            adTxt.eq(index).children("p").css({paddingTop: "50px", paddingBottom: "50px"}).stop(false, true).animate({paddingTop: "0", paddingBottom: "0"}, time);
            adTxt.eq(index).css({top: "0", opacity: "0"}).stop(false, true).animate({top: "110px", opacity: "1"}, time);
            adImg.eq(index).css({right: "-50px", opacity: "0"}).stop(false, true).animate({right: "10px", opacity: "1"}, time);
        }, 200)
        curIndex = index;
    }
    //Banner End
    //Cases Start
    $("#caseslist>.cases>li").live({mouseenter: function () {
        $("p", this).stop(false, true).slideDown("normal", "easeOutQuad");
    }, mouseleave: function () {
        $("p", this).stop(false, true).slideUp("normal", "easeOutQuad");
    }});
    $("#caseslist>.cases>li>img,#newsbox>ul>li>a>img").lazyload({effect: "fadeIn", failurelimit: 10});
    //Cases End
    //nav start
    (function () {
        var nav = $("#service ul");
        var lis = nav.children("li");
        var arrow = $(".arrow").css("left");
        var speed = 300;
        var n = 0;
        //取cur位置
        for (var i = 0; i < lis.length; i++) {
            if (lis.eq(i).attr("class") == "cur") {
                n = i;
            }
        }
        lis.eq(0).hover(function () {
            $(".arrow").stop(true, true).animate({left: "0px"}, speed);
            lis.removeClass("cur");
            $(this).addClass("cur");
        })
        lis.eq(1).hover(function () {
            $(".arrow").stop(true, true).animate({left: "370px"}, speed);
            lis.removeClass("cur");
            $(this).addClass("cur");
        })
        lis.eq(2).hover(function () {
            $(".arrow").stop(true, true).animate({left: "738px"}, speed);
            lis.removeClass("cur");
            $(this).addClass("cur");
        })
        nav.mouseleave(function () {
            $(".arrow").stop(true, true).animate({left: arrow}, speed);
            lis.removeClass("cur");
            lis.eq(n).addClass("cur");
        })
    }())
    //]]>
</script>

app/views/comment/_kefu.html.erb
<!-- 客服 -->
<div class="serviceleft">
  <div class="si_serviceleft">
    <div class="si_serviceleft2" style="display: block;">
      <ul>
        <li class="si_serviceleftLI1" style="">
          <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=208263915&site=qq&menu=yes">
            朋兴客服
          </a>
        </li>
        <li class="si_serviceleftLI1" style="">
          <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2544481839&site=qq&menu=yes">
            朋兴客服
          </a>
        </li>
        <li class="si_serviceleftLI2" style="">
          <div style="display: none;"><img src="/images/weixin/wx2wm.png" alt="朋兴传媒微信"></div>
        </li>
      </ul>
    </div>
  </div>
</div>
<script>
    $(function () {
        $(".si_serviceleftLast").hover(function () {
            $(".si_serviceleftLast div").fadeIn(0);
        }, function () {
            $(".si_serviceleftLast div").fadeOut(0);
        })
        $(".si_serviceleftLI2").hover(function () {
            $(".si_serviceleftLI2 div").fadeIn(0);
        }, function () {
            $(".si_serviceleftLI2 div").fadeOut(0);
        })
        $(".si_serviceleft2 ul li").hover(function () {
            $(this).css('background-color', '#d93d69');
        }, function () {
            $(this).css('background-color', '');
        })
    })
</script>

app/views/comment/_menu.html.erb
<ul>
  <li class="home hover" style="opacity: 1; background-position-y: -37px;">
    <a href="<%= root_path %>" title="长春朋兴首页">首页</a></li>
  <li class="nav1" style="opacity: 1; background-position-y: -37px;">
    <a href="http://wx.pxwgj.com" title="长春朋兴关于">微平台</a></li>
  <li class="nav2" style="opacity: 1; background-position-y: -37px;">
    <a href="<%= website_services_path %>" title="长春朋兴服务">服务</a></li>
  <li class="nav3" style="opacity: 1; background-position-y: -37px;">
    <a href="<%= cases_path %>" title="长春朋兴案例">案例</a></li>
  <li class="nav4" style="opacity: 1; background-position-y: -37px;">
    <a href="<%= contact_index_path %>" title="长春朋兴案例">联系方式</a></li>
</ul>