config/routes.rb
Weixin::Application.routes.draw do
  resources :mains
  resources :cccabouts do
    collection do
      get 'disclaimer'
      get 'privacy'
      get 'job'
      get 'contact'
      get 'links'
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  root :to => "main#index"
  resources :mains
  resources :services do
    collection do
      get 'website'
      get 'marketing'
    end
  end
  resources :abouts
  resources :cases
  resources :contact
  resources :questions
  resources :weixin do
    collection do
      get 'contrast'
    end
  end
  resources :news
  namespace :admin do
    match '' => 'cases#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end
    resources :cases
    resources :questions
    resources :journalisms
    resources :jobs
    resources :cccshs
  end

end

app/models/case.rb
class Case < ActiveRecord::Base
  validates :title, :presence => {:message => "案例标题不能为空！"}, :length => {:maximum => 15, :message => "题目长度不能超过15"}
  validates :content, :presence => {:message => "案例内容不能为空！"}, :length => {:maximum => 200, :message => "案例内容长度不能超过200"}

  attr_accessor :avatar
  has_attached_file :avatar, :styles => {:zhengchang => "350x210>", :thumb => "70x42>", :anli => "480x800>"}, :default_url => "/images/:style/missing.png",
                    :url => "/case/:id_partition/:style/:filename"
  validates_attachment_size :avatar, :less_than => 2.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/png', 'image/x-png', 'image/jpeg', 'image/pjpeg', 'image/jpg']

  scope :order_ct_desc, lambda { order("created_at DESC") }

  @filepath="public/cases/"
  @previewpath = "previews/"

  # 删除图片
  def self.deletefile(r_id)
    idstr = format("%09d", r_id.to_s)
    one_path = @filepath+idstr[0, 3]+"/"
    two_path = one_path + idstr[3, 3]+"/"
    three_path = two_path + idstr[6, 3]+"/"
    begin
      `rm -rf #{Rails.root+three_path}`
    rescue
      if system "rm -rf #{Rails.root+three_path}"
        return true
      else
        return false
      end
    end
    return true
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/journalism.rb
class Journalism < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/main.rb
class Main < ActiveRecord::Base

  validates :name, :presence => {:message => "姓名不能为空！"}
  validates :tel, :presence => {:message => "电话不能为空！"}
  validates :address, :presence => {:message => "地址不能为空！"}
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/zhaoshang.rb
class Zhaoshang < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def index
    @roll = Case.all.order_ct_desc.page(params[:page]).per(30)
  end

  def show
    @roll = Case.find params[:id]
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @questions = Question.order_ct_desc.page(params[:page]).per(3)
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
    @roll = Case.all.order_ct_desc.page(params[:page]).per(16)
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only: [:show, :edit, :update, :destroy]
  layout 'admin_no_sider'

  # GET /mains
  # GET /mains.json
  def index
    @mains = Main.all
  end

  # GET /mains/1
  # GET /mains/1.json
  def show
  end

  # GET /mains/new
  def new
    @main = Main.new
  end


  # POST /mains
  # POST /mains.json
  def create
    @main = Main.new(main_params)

    respond_to do |format|
      if @main.save
        format.html { redirect_to @main, notice: '您已注册成功，请点击返回首页' }
        format.json { render :show, status: :created, location: @main }
      else
        format.html { render :new }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1
  # DELETE /mains/1.json
  def destroy
    @main.destroy
    respond_to do |format|
      format.html { redirect_to mains_url, notice: 'Main was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_main
    @main = Main.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def main_params
    params.require(:main).permit(:name, :tel, :address)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @roll = Case.all.order_ct_desc.page(params[:page]).per(10)
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
  end

  def show
    @journalism = Journalism.find params[:id]
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def website
  end

  def marketing
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_datetime_format(datetime)
    datetime.strftime(" %Y年%m月%d日 %H:%M:%S")
  end

  def my_time_format(datetime)
    datetime.strftime(" %Y-%m-%d")
  end

  def truncate_u(text, length = 30, truncate_string = "...")
    l=0
    char_array=text.unpack("U*")
    char_array.each_with_index do |c, i|
      l = l+ (c<127 ? 0.5 : 1)
      if l>=length
        return char_array[0..i].pack("U*")+(i<char_array.length-1 ? truncate_string : "")
      end
    end
    return text
  end

  def my_datetime(datetime)
    datetime.strftime(" %Y.%m.%d")
  end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/cccabouts_helper.rb
module CccaboutsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/weixin_helper.rb
module WeixinHelper
end

app/views/services/marketing.html.erb
<body id="con">
<header>
  <div class="wrapper">
    <h1 class="logo">
      <a href="<%= marketing_services_path %>" title=""><img src="../images/logo_2.png" width="127" height="128" alt=""><strong>服务</strong><span>SERVICES</span></a>
    </h1>
    <nav>
      <%= render "comment/menu" %>
    </nav>
  </div>
</header>
<!-- /header -->
<section id="service_c">

  <ul class="catbtn">
    <li class="website" style="opacity: 1; background-position-y: 0px;">
      <a href="<%= website_services_path %>" title="品牌网站建设">成都网站建设</a></li>
    <li class="seosite" style="opacity: 1; background-position-y: -188px;">
      <a href="<%= marketing_services_path %>" title="网站SEO推广">成都网站推广</a></li>
    <li class="weixinsite"><a href="<%= weixin_index_path %>" title="微信公众平台开发" target="_blank">成都微站开发,微网站开发</a></li>
  </ul>
  <div style="width:1060px; margin:0 auto;">
    <div class="websitebox" id="servicebox" style="padding: 40px 40px 0px; display: none;">
      <div class="hide">关闭</div>
      <h1>你的网站是否够称职？</h1>

      <p>028能够帮您搭建适应各种设备及浏览器访问、针对主流搜索引擎优化、用户体验良好的网站。<br>深入剖析企业需求，致力于树立良好的企业品牌形象，完善企业对内外的传播需求。积极协助企业找到发展战略核心，从战略的角度树立企业的品牌形象。
      </p>

      <div class="websitebox1">
        <h3>能否被搜索引擎收录并排在前列？<em>+ MORE</em></h3>

        <p class="hide">在中国,百度一家独大,占据了大约64.47%的市场份额，所以一个网站是否能被百度友好的收录很重要！你现在能来到的网站，也许就是通过百度！</p>

        <h3>换个浏览器网站就打不开？<em>+ MORE</em></h3>

        <p class="hide">兼容性不够的话会影响访问网站的速度，一般是超过3秒载入，访问者就会流失。</p>

        <h3>网站还没上线，设计已经落后了！<em>+ MORE</em></h3>

        <p class="hide">四亿手机网站已经习惯用手机浏览网站，大部分的网站设计公司仅仅停留在制作pc网站。</p>
      </div>
      <div id="con_intro">
        <h2>
          出色的网站设计，特别是028原创设计团队制作的网站<span>必须具备以下特点</span>
        </h2>
        <ul class="loop clearfix">
          <li class="fl">
            <img src="../images/website_03.gif">

            <h3>代码清爽规范标准，方便后期维护</h3>

            <p>零二八遵循行业标准代码，追求新技术html5、CSS3、Ajax</p>
          </li>
          <li class="fr">
            <img src="../images/website_05.gif">

            <h3>兼容各大浏览器</h3>

            <p>针对时下流行浏览器进行优化，IE、chrome、safari、firefox、360，opera一个也不落下。</p>
          </li>
          <li class="s"></li>
          <li class="fl">
            <img src="../images/website_10.gif">

            <h3>设计上的原创性，界面不雷同</h3>

            <p>原创设计，是在刷新固有的经典界面之后呈现出破土而出的生命气息，是在展现某种被忽视的体验，并预设着新的可能性。零二八做到了！</p>
          </li>
          <li class="fr">
            <img src="../images/website_12.gif">

            <h3>在企业、商城上的丰富经验</h3>

            <p>零二八在企业、商城等行业网站建设有丰富经验，每一天我们都在刷新行业纪录。</p>
          </li>
          <li class="s"></li>
          <li class="fl">
            <img src="../images/website_17.gif">

            <h3>视频支持多平台环境播放</h3>

            <p>视频支持在PC、iPhone、iPad、安卓等环境播放</p>
          </li>
          <li class="fr">
            <img src="../images/website_19.gif">

            <h3>有针对手机、平板客户端网站的丰富设计经验</h3>

            <p>依托多屏优化技术，能够保证用户在使用PC、手机或者平板访问网站时都能够获得最佳的用户体验。</p>
          </li>
          <li class="s"></li>
        </ul>
      </div>

      <div class="service_case">
        <h3>经典案例</h3><span><a href="http://www.028studio.com/028/CASES/">更多案例</a></span>
        <ul>
          <img src="../images/case_logo1.png">
          <img src="../images/case_logo2.png">
          <img src="../images/case_logo3.png">
        </ul>
      </div>

    </div>
    <div class="seositebox" id="servicebox" style="display: block;">
      <div class="hide">关闭</div>
      <div class="seositeboxlist">
        <h1>什么是网站推广?</h1>
        <span>成千上万的同行网站，让客户立刻找到你</span>

        <p>SEO整站优化就是通过对网站定位、网站结构及网站内容的整体优化，确保网站所有页面都具备搜索引擎友好性保证页面内容被搜索引擎收录让网站在百度等搜索引擎都有比较高的好的整体排名表现。</p>
        <img src="../images/seo_11.gif" title="什么是网站推广？">
      </div>
      <div class="seositeboxlist" style=" padding:0 39px">
        <h1>为什么要做网站推广?</h1>
        <span>做完网站就够了吗？网站推广的意义等同于广告</span>

        <p>企业网站本身就是为了宣传企业及企业的产品和服务而诞生的，网站做好之后如果被埋没在众多同行的网站之中让客户无法看到，岂不是失去了做网站的意义。
          <br>
          现在很多客户已经了解到网站推广的重要性，知道百度竞价推广，而我们所说的网站推广（即SEO网站优化）和百度竞价推广又有何区别呢？</p>
        <em>如何建立一个成功的网站？</em>
        <img src="../images/service-seo_21.gif" title="为什么要做网站推广？" style="margin-top:20px;">
      </div>
      <div class="seositeboxlist">
        <h1>SEO与百度竞价的区别</h1>
        <span>点击免费，提高网站在所有搜索引擎的排名</span>

        <p>搜索引擎优化其实和百度的竞价排名是一个道理，最终的结果就是让网站在各大搜索引擎里有较好的排名，从而让你的访客更容易找到你！让你的网站在竞争中脱颖而出！</p>
        <table border="1" cellspacing="0" cellpadding="0" width="100%">
          <tbody>
          <tr>
            <td class="s_1">关键项</td>
            <td class="s_1">百度竞价</td>
            <td class="s_1">SEO</td>
          </tr>
          <tr>
            <td><strong>费用</strong></td>
            <td>按点击付费</td>
            <td>按年收取固定费用</td>
          </tr>
          <tr>
            <td><strong>点击量</strong></td>
            <td>在费用范围内点击</td>
            <td>不限</td>
          </tr>
          <tr>
            <td><strong>形象展现</strong></td>
            <td>推广位置</td>
            <td>自然排名</td>
          </tr>
          <tr>
            <td><strong>针对范围</strong></td>
            <td>百度</td>
            <td>各大搜索引擎</td>
          </tr>
          </tbody>
        </table>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</section>

<script type="text/javascript" src="./javascripts/jquery-1.7.2.min.js"></script>
<script src="./javascripts/navigatora1.js" defer="defer" type="text/javascript"></script>
<script type="text/javascript" src="./javascripts/jquery.plugin.min.js"></script>
<script type="text/javascript" src="./javascripts/jquery.SuperSlide.2.1.1.js"></script>

<script type="text/javascript">
    $(".website").click(function () {
        $(".websitebox").slideDown("slow");
        $(".website").animate({"background-position-y": "-188px", opacity: "1"}, {duration: "normal", easing: "swing"});
        $(".seositebox").hide(100);
        $(".seosite").animate({"background-position-y": "0", opacity: "1"}, {duration: "normal", easing: "swing"});//鼠标out的样子
    });
    $(".seosite").click(function () {
        $(".seositebox").slideDown("slow");
        $(".seosite").animate({"background-position-y": "-188px", opacity: "1"}, {duration: "normal", easing: "swing"});
        $(".websitebox").hide(100);
        $(".website").animate({"background-position-y": "0", opacity: "1"}, {duration: "normal", easing: "swing"});//鼠标out的样子
    });
    $("#servicebox div.hide").click(function () {
        $(this).parents("#servicebox").hide("slow");
    });
</script>
<script type="text/javascript">jQuery(".websitebox1").slide({titCell: "h3", targetCell: "P", defaultIndex: 1, effect: "slideDown", delayTime: 300, trigger: "click", triggerTime: 300, defaultPlay: false, returnDefault: true});</script>


</body>
<%= render "comment/footer" %>

app/views/services/website.html.erb
<body id="con">
<header>
  <div class="wrapper">
    <h1 class="logo">
      <a href="<%= website_services_path %>" title=""><img src="../images/logo_2.png" width="127" height="128" alt=""><strong>服务</strong><span>SERVICES</span></a>
    </h1>
    <nav>
      <%= render "comment/menu" %>
    </nav>
  </div>
</header>
<!-- /header -->
<section id="service_c">
  <ul class="catbtn">
    <li class="website" style="opacity: 1; background-position-y: -188px;">
      <a href="<%= website_services_path %>" title="品牌网站建设">成都网站建设</a></li>
    <li class="seosite" style="opacity: 1; background-position-y: 0px;">
      <a href="<%= marketing_services_path %>" title="网站SEO推广">成都网站推广</a></li>
    <li class="weixinsite"><a href="<%= weixin_index_path %>" title="微信公众平台开发" target="_blank">成都微站开发,微网站开发</a></li>
  </ul>
  <div style="width:1060px; margin:0 auto;">
    <div class="websitebox" id="servicebox" style="padding: 40px 40px 0px; display: block;">
      <div class="hide">关闭</div>
      <h1>你的网站是否够称职？</h1>

      <p>028能够帮您搭建适应各种设备及浏览器访问、针对主流搜索引擎优化、用户体验良好的网站。<br>深入剖析企业需求，致力于树立良好的企业品牌形象，完善企业对内外的传播需求。积极协助企业找到发展战略核心，从战略的角度树立企业的品牌形象。
      </p>

      <div class="websitebox1">
        <h3>能否被搜索引擎收录并排在前列？<em>+ MORE</em></h3>

        <p class="hide">在中国,百度一家独大,占据了大约64.47%的市场份额，所以一个网站是否能被百度友好的收录很重要！你现在能来到的网站，也许就是通过百度！</p>

        <h3>换个浏览器网站就打不开？<em>+ MORE</em></h3>

        <p class="hide">兼容性不够的话会影响访问网站的速度，一般是超过3秒载入，访问者就会流失。</p>

        <h3>网站还没上线，设计已经落后了！<em>+ MORE</em></h3>

        <p class="hide">四亿手机网站已经习惯用手机浏览网站，大部分的网站设计公司仅仅停留在制作pc网站。</p>
      </div>
      <div id="con_intro">
        <h2>
          出色的网站设计，特别是028原创设计团队制作的网站<span>必须具备以下特点</span>
        </h2>
        <ul class="loop clearfix">
          <li class="fl">
            <img src="../images/website_03.gif">

            <h3>代码清爽规范标准，方便后期维护</h3>

            <p>零二八遵循行业标准代码，追求新技术html5、CSS3、Ajax</p>
          </li>
          <li class="fr">
            <img src="../images/website_05.gif">

            <h3>兼容各大浏览器</h3>

            <p>针对时下流行浏览器进行优化，IE、chrome、safari、firefox、360，opera一个也不落下。</p>
          </li>
          <li class="s"></li>
          <li class="fl">
            <img src="../images/website_10.gif">

            <h3>设计上的原创性，界面不雷同</h3>

            <p>原创设计，是在刷新固有的经典界面之后呈现出破土而出的生命气息，是在展现某种被忽视的体验，并预设着新的可能性。零二八做到了！</p>
          </li>
          <li class="fr">
            <img src="../images/website_12.gif">

            <h3>在企业、商城上的丰富经验</h3>

            <p>零二八在企业、商城等行业网站建设有丰富经验，每一天我们都在刷新行业纪录。</p>
          </li>
          <li class="s"></li>
          <li class="fl">
            <img src="../images/website_17.gif">

            <h3>视频支持多平台环境播放</h3>

            <p>视频支持在PC、iPhone、iPad、安卓等环境播放</p>
          </li>
          <li class="fr">
            <img src="../images/website_19.gif">

            <h3>有针对手机、平板客户端网站的丰富设计经验</h3>

            <p>依托多屏优化技术，能够保证用户在使用PC、手机或者平板访问网站时都能够获得最佳的用户体验。</p>
          </li>
          <li class="s"></li>
        </ul>
      </div>

      <div class="service_case">
        <h3>经典案例</h3><span><a href="<%= cases_path %>">更多案例</a></span>
        <ul>
          <img src="../images/case_logo1.png">
          <img src="../images/case_logo2.png">
          <img src="../images/case_logo3.png">
        </ul>
      </div>

    </div>
    <div class="seositebox" id="servicebox" style="display: none;">
      <div class="hide">关闭</div>
      <div class="seositeboxlist">
        <h1>什么是网站推广?</h1>
        <span>成千上万的同行网站，让客户立刻找到你</span>

        <p>SEO整站优化就是通过对网站定位、网站结构及网站内容的整体优化，确保网站所有页面都具备搜索引擎友好性保证页面内容被搜索引擎收录让网站在百度等搜索引擎都有比较高的好的整体排名表现。</p>
        <img src="../images/seo_11.gif" title="什么是网站推广？">
      </div>
      <div class="seositeboxlist" style=" padding:0 39px">
        <h1>为什么要做网站推广?</h1>
        <span>做完网站就够了吗？网站推广的意义等同于广告</span>

        <p>企业网站本身就是为了宣传企业及企业的产品和服务而诞生的，网站做好之后如果被埋没在众多同行的网站之中让客户无法看到，岂不是失去了做网站的意义。
          <br>
          现在很多客户已经了解到网站推广的重要性，知道百度竞价推广，而我们所说的网站推广（即SEO网站优化）和百度竞价推广又有何区别呢？</p>
        <em>如何建立一个成功的网站？</em>
        <img src="../images/service-seo_21.gif" title="为什么要做网站推广？" style="margin-top:20px;">
      </div>
      <div class="seositeboxlist">
        <h1>SEO与百度竞价的区别</h1>
        <span>点击免费，提高网站在所有搜索引擎的排名</span>

        <p>搜索引擎优化其实和百度的竞价排名是一个道理，最终的结果就是让网站在各大搜索引擎里有较好的排名，从而让你的访客更容易找到你！让你的网站在竞争中脱颖而出！</p>
        <table border="1" cellspacing="0" cellpadding="0" width="100%">
          <tbody>
          <tr>
            <td class="s_1">关键项</td>
            <td class="s_1">百度竞价</td>
            <td class="s_1">SEO</td>
          </tr>
          <tr>
            <td><strong>费用</strong></td>
            <td>按点击付费</td>
            <td>按年收取固定费用</td>
          </tr>
          <tr>
            <td><strong>点击量</strong></td>
            <td>在费用范围内点击</td>
            <td>不限</td>
          </tr>
          <tr>
            <td><strong>形象展现</strong></td>
            <td>推广位置</td>
            <td>自然排名</td>
          </tr>
          <tr>
            <td><strong>针对范围</strong></td>
            <td>百度</td>
            <td>各大搜索引擎</td>
          </tr>
          </tbody>
        </table>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</section>

<script type="text/javascript" src="../javascripts/jquery-1.7.2.min.js"></script>
<script src="../javascripts/navigatora1.js" defer="defer" type="text/javascript"></script>
<script type="text/javascript" src="../javascripts/jquery.plugin.min.js"></script>
<script type="text/javascript" src="../javascripts/jquery.SuperSlide.2.1.1.js"></script>

<script type="text/javascript">
    $(".website").click(function () {
        $(".websitebox").slideDown("slow");
        $(".website").animate({"background-position-y": "-188px", opacity: "1"}, {duration: "normal", easing: "swing"});
        $(".seositebox").hide(100);
        $(".seosite").animate({"background-position-y": "0", opacity: "1"}, {duration: "normal", easing: "swing"});//鼠标out的样子
    });
    $(".seosite").click(function () {
        $(".seositebox").slideDown("slow");
        $(".seosite").animate({"background-position-y": "-188px", opacity: "1"}, {duration: "normal", easing: "swing"});
        $(".websitebox").hide(100);
        $(".website").animate({"background-position-y": "0", opacity: "1"}, {duration: "normal", easing: "swing"});//鼠标out的样子
    });
    $("#servicebox div.hide").click(function () {
        $(this).parents("#servicebox").hide("slow");
    });
</script>
<script type="text/javascript">jQuery(".websitebox1").slide({titCell: "h3", targetCell: "P", defaultIndex: 1, effect: "slideDown", delayTime: 300, trigger: "click", triggerTime: 300, defaultPlay: false, returnDefault: true});</script>
</body>
<%= render "comment/footer" %>