config/routes.rb
Weixin::Application.routes.draw do
  resources :mains
  resources :cccabouts do
    collection do
      get 'disclaimer'
      get 'privacy'
      get 'job'
      get 'contact'
      get 'links'
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  root :to => "main#index"
  resources :mains
  resources :services do
    collection do
      get 'website'
      get 'marketing'
    end
  end
  resources :abouts
  resources :cases
  resources :contact
  resources :questions
  resources :weixin do
    collection do
      get 'contrast'
    end
  end
  resources :news
  namespace :admin do
    match '' => 'cases#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end
    resources :cases
    resources :questions
    resources :journalisms
    resources :jobs
    resources :cccshs
  end

end

app/models/case.rb
class Case < ActiveRecord::Base
  validates :title, :presence => {:message => "案例标题不能为空！"}, :length => {:maximum => 15, :message => "题目长度不能超过15"}
  validates :content, :presence => {:message => "案例内容不能为空！"}, :length => {:maximum => 200, :message => "案例内容长度不能超过200"}

  attr_accessor :avatar
  has_attached_file :avatar, :styles => {:zhengchang => "350x210>", :thumb => "70x42>", :anli => "480x800>"}, :default_url => "/images/:style/missing.png",
                    :url => "/case/:id_partition/:style/:filename"
  validates_attachment_size :avatar, :less_than => 2.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/png', 'image/x-png', 'image/jpeg', 'image/pjpeg', 'image/jpg']

  scope :order_ct_desc, lambda { order("created_at DESC") }

  @filepath="public/cases/"
  @previewpath = "previews/"

  # 删除图片
  def self.deletefile(r_id)
    idstr = format("%09d", r_id.to_s)
    one_path = @filepath+idstr[0, 3]+"/"
    two_path = one_path + idstr[3, 3]+"/"
    three_path = two_path + idstr[6, 3]+"/"
    begin
      `rm -rf #{Rails.root+three_path}`
    rescue
      if system "rm -rf #{Rails.root+three_path}"
        return true
      else
        return false
      end
    end
    return true
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/journalism.rb
class Journalism < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/main.rb
class Main < ActiveRecord::Base

  validates :name, :presence => {:message => "姓名不能为空！"}
  validates :tel, :presence => {:message => "电话不能为空！"}
  validates :address, :presence => {:message => "地址不能为空！"}
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/zhaoshang.rb
class Zhaoshang < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/controllers/admin/journalisms_controller.rb
class Admin::JournalismsController < Admin::MainController
  layout 'admin'

  def index
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
  end

  def new
    @journalism = Journalism.new
  end

  def create
    @journalism = Journalism.new(
        :title => params[:journalism][:title],
        :description => params[:journalism][:description]
    )
    if @journalism.save
      flash[:note] = "创建成功"
      redirect_to admin_journalisms_path and return
    else
      flash[:error_msg] = @journalism.errors.values.join(";    ")
      redirect_to :back and return
    end
  end

  def edit
    @journalism = Journalism.find(params[:id])
  end

  def update
    @category = Journalism.find(params[:id])
    update_category = @category.update_attributes(
        :title => params[:journalism][:title],
        :description => params[:journalism][:description]
    )
    if update_category
      respond_to do |category|
        category.html {
          redirect_to admin_journalisms_path and return
        }
      end
    end
  end

  def show
    @journalism = Journalism.find params[:id]
  end

  #   删除
  def destroy
    @journalism = Journalism.find(params[:id])
    flash[:error_msg] = @journalism.destroy ? "删除成功" : "请稍后再试"
    redirect_to admin_journalisms_path and return
  end
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def index
    @roll = Case.all.order_ct_desc.page(params[:page]).per(30)
  end

  def show
    @roll = Case.find params[:id]
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @questions = Question.order_ct_desc.page(params[:page]).per(3)
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
    @roll = Case.all.order_ct_desc.page(params[:page]).per(16)
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only: [:show, :edit, :update, :destroy]
  layout 'admin_no_sider'

  # GET /mains
  # GET /mains.json
  def index
    @mains = Main.all
  end

  # GET /mains/1
  # GET /mains/1.json
  def show
  end

  # GET /mains/new
  def new
    @main = Main.new
  end


  # POST /mains
  # POST /mains.json
  def create
    @main = Main.new(main_params)

    respond_to do |format|
      if @main.save
        format.html { redirect_to @main, notice: '您已注册成功，请点击返回首页' }
        format.json { render :show, status: :created, location: @main }
      else
        format.html { render :new }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1
  # DELETE /mains/1.json
  def destroy
    @main.destroy
    respond_to do |format|
      format.html { redirect_to mains_url, notice: 'Main was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_main
    @main = Main.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def main_params
    params.require(:main).permit(:name, :tel, :address)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @roll = Case.all.order_ct_desc.page(params[:page]).per(10)
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
  end

  def show
    @journalism = Journalism.find params[:id]
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/journalisms_helper.rb
module Admin::JournalismsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_datetime_format(datetime)
    datetime.strftime(" %Y年%m月%d日 %H:%M:%S")
  end

  def my_time_format(datetime)
    datetime.strftime(" %Y-%m-%d")
  end

  def truncate_u(text, length = 30, truncate_string = "...")
    l=0
    char_array=text.unpack("U*")
    char_array.each_with_index do |c, i|
      l = l+ (c<127 ? 0.5 : 1)
      if l>=length
        return char_array[0..i].pack("U*")+(i<char_array.length-1 ? truncate_string : "")
      end
    end
    return text
  end

  def my_datetime(datetime)
    datetime.strftime(" %Y.%m.%d")
  end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/cccabouts_helper.rb
module CccaboutsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/weixin_helper.rb
module WeixinHelper
end

app/views/admin/journalisms/edit.html.erb
<script>
    <% if flash[:error_msg]%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_journalisms_path %>">新闻管理</a> <span class="divider">/</span>
    </li>
    <li>
      新闻修改
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 新闻修改</h2>
    </div>
    <div class="box-content">
      <%= form_for @journalism, :url => admin_journalism_path, :method => "put", :html => {:id => "verifytitle", :class => "form-horizontal"} do |f| %>
          <legend>新闻修改</legend>
          <%= f.label "新闻标题：" %>
          <%= f.text_field :title %>
          <br/>
          <%= f.label "新闻内容：" %>
          <%= f.cktext_area :description %>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">完成提交</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script src="/admin/js/jquery.validate.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#verifytitle").validate({
                rules: {
                    "journalism[title]": {
                        required: true
                    },

                    "journalism[description]": {
                        required: true
                    }
                },
                messages: {
                    "journalism[title]": {
                        required: "请填写标题"
                    },
                    "journalism[description]": {
                        required: "请填写内容"
                    }
                },
                errorClass: "error",
                highlight: function (element, errorClass) {
                    $(element).parent().parent().addClass(errorClass);
                },
                unhighlight: function (element, errorClass) {
                    $(element).parent().parent().removeClass(errorClass);
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                },
                errorElement: "span"
            });
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>

app/views/admin/journalisms/index.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      新闻列表
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i> 新闻列表</h2>
    </div>
    <div class="box-content">
      <div class="form-actions">
        <div style="float: left">
          <%= link_to '添加新闻', new_admin_journalism_path, :class => "btn btn-primary" %>
        </div>
      </div>
      <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
        <tr>
          <th>ID</th>
          <th>新闻标题</th>
          <th>创建时间</th>
          <th>新闻详细</th>
          <th>新闻修改</th>
          <th>新闻删除</th>
        </tr>
        </thead>
        <tbody>
        <% @journalisms.each do |q| %>
            <tr>
              <td><%= q.id %></td>
              <td><%= truncate_u(q.title, 10) %></td>
              <td class="center"><%= my_datetime_format q.created_at %></td>
              <td class="center"><%= link_to "查看", admin_journalism_path(q) %></td>
              <td><%= link_to '修改', edit_admin_journalism_path(q) %></td>
              <td><%= link_to '删除', admin_journalism_path(q), :method => :delete, :confirm => "您确定要删除吗?" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination pagination-centered">
        <ul>
          <%= paginate @journalisms %>
        </ul>
      </div>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->

app/views/admin/journalisms/new.html.erb
<script>
    <% if flash[:error_msg]%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_journalisms_path %>">新闻管理</a> <span class="divider">/</span>
    </li>
    <li>
      添加新闻
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 添加新闻</h2>
    </div>
    <div class="box-content">
      <%= form_for(:journalism, :url => admin_journalisms_path, :method => :post, :html => {:id => "verifytitle"}) do |f| %>
          <legend>添加新闻</legend>
          <%= f.label "新闻标题：" %>
          <%= f.text_field :title %>
          <%= f.label "新闻内容：" %>
          <%= f.cktext_area :description %>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">完成提交</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script src="/admin/js/jquery.validate.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#verifytitle").validate({
                rules: {
                    "journalism[title]": {
                        required: true
                    },

                    "journalism[description]": {
                        required: true
                    }
                },
                messages: {
                    "journalism[title]": {
                        required: "请填写标题"
                    },
                    "journalism[description]": {
                        required: "请填写内容"
                    }
                },
                errorClass: "error",
                highlight: function (element, errorClass) {
                    $(element).parent().parent().addClass(errorClass);
                },
                unhighlight: function (element, errorClass) {
                    $(element).parent().parent().removeClass(errorClass);
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                },
                errorElement: "span"
            });
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>

app/views/admin/journalisms/show.html.erb
<div>
  <ul class="breadcrumb">
    <li>
      <a href=#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_journalisms_path %>">新闻管理</a> <span class="divider">/</span>
    </li>
    <li>
      新闻详细
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-content">
      <p>
        新闻标题：<%= @journalism.title %>
      </p><br/>

      <p>
        新闻内容：<%= @journalism.description.html_safe %>
      </p>

      <br/><br/>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->