config/routes.rb
Weixin::Application.routes.draw do
  resources :mains
  resources :cccabouts do
    collection do
      get 'disclaimer'
      get 'privacy'
      get 'job'
      get 'contact'
      get 'links'
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  root :to => "main#index"
  resources :mains
  resources :services do
    collection do
      get 'website'
      get 'marketing'
    end
  end
  resources :abouts
  resources :cases
  resources :contact
  resources :questions
  resources :weixin do
    collection do
      get 'contrast'
    end
  end
  resources :news
  namespace :admin do
    match '' => 'cases#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end
    resources :cases
    resources :questions
    resources :journalisms
    resources :jobs
    resources :cccshs
  end

end

app/models/case.rb
class Case < ActiveRecord::Base
  validates :title, :presence => {:message => "案例标题不能为空！"}, :length => {:maximum => 15, :message => "题目长度不能超过15"}
  validates :content, :presence => {:message => "案例内容不能为空！"}, :length => {:maximum => 200, :message => "案例内容长度不能超过200"}

  attr_accessor :avatar
  has_attached_file :avatar, :styles => {:zhengchang => "350x210>", :thumb => "70x42>", :anli => "480x800>"}, :default_url => "/images/:style/missing.png",
                    :url => "/case/:id_partition/:style/:filename"
  validates_attachment_size :avatar, :less_than => 2.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/png', 'image/x-png', 'image/jpeg', 'image/pjpeg', 'image/jpg']

  scope :order_ct_desc, lambda { order("created_at DESC") }

  @filepath="public/cases/"
  @previewpath = "previews/"

  # 删除图片
  def self.deletefile(r_id)
    idstr = format("%09d", r_id.to_s)
    one_path = @filepath+idstr[0, 3]+"/"
    two_path = one_path + idstr[3, 3]+"/"
    three_path = two_path + idstr[6, 3]+"/"
    begin
      `rm -rf #{Rails.root+three_path}`
    rescue
      if system "rm -rf #{Rails.root+three_path}"
        return true
      else
        return false
      end
    end
    return true
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/journalism.rb
class Journalism < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/main.rb
class Main < ActiveRecord::Base

  validates :name, :presence => {:message => "姓名不能为空！"}
  validates :tel, :presence => {:message => "电话不能为空！"}
  validates :address, :presence => {:message => "地址不能为空！"}
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/models/zhaoshang.rb
class Zhaoshang < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}
  validates :description, :presence => {:message => "请填写内容"}
  scope :order_ct_desc, lambda { order("created_at DESC") }
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
  end
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def index
    @roll = Case.all.order_ct_desc.page(params[:page]).per(30)
  end

  def show
    @roll = Case.find params[:id]
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @questions = Question.order_ct_desc.page(params[:page]).per(3)
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
    @roll = Case.all.order_ct_desc.page(params[:page]).per(16)
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only: [:show, :edit, :update, :destroy]
  layout 'admin_no_sider'

  # GET /mains
  # GET /mains.json
  def index
    @mains = Main.all
  end

  # GET /mains/1
  # GET /mains/1.json
  def show
  end

  # GET /mains/new
  def new
    @main = Main.new
  end


  # POST /mains
  # POST /mains.json
  def create
    @main = Main.new(main_params)

    respond_to do |format|
      if @main.save
        format.html { redirect_to @main, notice: '您已注册成功，请点击返回首页' }
        format.json { render :show, status: :created, location: @main }
      else
        format.html { render :new }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1
  # DELETE /mains/1.json
  def destroy
    @main.destroy
    respond_to do |format|
      format.html { redirect_to mains_url, notice: 'Main was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_main
    @main = Main.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def main_params
    params.require(:main).permit(:name, :tel, :address)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @roll = Case.all.order_ct_desc.page(params[:page]).per(10)
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
  end

  def show
    @journalism = Journalism.find params[:id]
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_datetime_format(datetime)
    datetime.strftime(" %Y年%m月%d日 %H:%M:%S")
  end

  def my_time_format(datetime)
    datetime.strftime(" %Y-%m-%d")
  end

  def truncate_u(text, length = 30, truncate_string = "...")
    l=0
    char_array=text.unpack("U*")
    char_array.each_with_index do |c, i|
      l = l+ (c<127 ? 0.5 : 1)
      if l>=length
        return char_array[0..i].pack("U*")+(i<char_array.length-1 ? truncate_string : "")
      end
    end
    return text
  end

  def my_datetime(datetime)
    datetime.strftime(" %Y.%m.%d")
  end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/cccabouts_helper.rb
module CccaboutsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/weixin_helper.rb
module WeixinHelper
end

app/views/news/index.html.erb
<body id="con">
<header>
  <div class="wrapper">
    <h1 class="logo">
      <a href="http://www.028studio.com/028/NEWS/" title=""><img src="./images/logo_5.png" width="127" height="128" alt=""/><strong>新闻中心</strong><span>NEWS</span></a>
    </h1>
    <nav>
      <%= render "comment/menu" %>
    </nav>
  </div>
</header>
<!-- /header -->
<section id="content">
  <div class="wrapper">
    <div class="contentbar">
      <div id="newslist">
        <ul class="news">
          <% @journalisms.each do |q| %>
              <li>
                <div class="newslist">
                  <a href="<%= news_path(q) %>" title="<%= q.title %>"><%= truncate_u(q.title, 50) %></a>
                  <span>UPTATED:<%= my_time_format q.created_at %></span>
                </div>
                <div class="clear"></div>
              </li>
          <% end %>
        </ul>
      </div>
      <div class="pager">
        <div class="pagination pagination-centered">
          <ul>
            <%= paginate @journalisms %>
          </ul>
        </div>
      </div>
    </div>
    <div class="sidebar">
      <h3 class="cat_title"><a href="<%= cases_path %>" title="案例">· 案例</a></h3>
      <% @roll.each do |roll| %>
          <h5>
            <a href="<%= case_path(roll) %>" title="<%= roll.title %>">
              <%= roll.title %>
            </a>
          </h5>
      <% end %>
    </div>
  </div>
</section>
</body>
<%= render "comment/footer" %>

app/views/news/show.html.erb
<body id="con">
<header>
  <div class="wrapper">
    <h1 class="logo">
      <a href="http://www.028studio.com/028/NEWS/" title=""><img src="../images/logo_5.png" width="127" height="128" alt=""><strong>新闻中心</strong><span>NEWS</span></a>
    </h1>
    <nav>
      <%= render "comment/menu" %>
    </nav>
  </div>
</header>
<!-- /header -->
<section id="content">
  <div class="wrapper">
    <br/>
    <br/>

    <div class="contentbar">
      <article>
        <h1 id="title">
          <span>UPTATED:<%= my_time_format @journalism.created_at %>
            <a href="<%= news_index_path %>" title="新闻中心">返回列表</a>
          </span>
          <%= @journalism.title %>
        </h1>
        <!--  分享代码   -->
        <div class="bdsharebuttonbox" style="float: right">
          <a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a><a href="#" class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a><a href="#" class="bds_tqf" data-cmd="tqf" title="分享到腾讯朋友"></a><a href="#" class="bds_kaixin001" data-cmd="kaixin001" title="分享到开心网"></a><a href="#" class="bds_ibaidu" data-cmd="ibaidu" title="分享到百度个人中心"></a><a href="#" class="bds_mshare" data-cmd="mshare" title="分享到一键分享"></a>
        </div>
        <script>window._bd_share_config = {"common": {"bdSnsKey": {}, "bdText": "", "bdMini": "2", "bdMiniList": false, "bdPic": "", "bdStyle": "0", "bdSize": "16"}, "share": {}, "image": {"viewList": ["qzone", "tsina", "tqq", "renren", "weixin", "sqq", "tqf", "kaixin001", "ibaidu", "mshare"], "viewText": "分享到：", "viewSize": "16"}, "selectShare": {"bdContainerClass": null, "bdSelectMiniList": ["qzone", "tsina", "tqq", "renren", "weixin", "sqq", "tqf", "kaixin001", "ibaidu", "mshare"]}};
        with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
        <br/>
        <!--  分享代码   -->
        <div id="info">
          <p>
            <%= @journalism.description.html_safe %>
          </p>
        </div>
      </article>
    </div>
    <div class="sidebar">
      <h3 class="cat_title">您可能感兴趣的！</h3>
      <% @journalisms.each do |q| %>
          <h5>
            <a href="<%= news_path(q) %>" title="<%= truncate_u(q.title, 15) %>">
              <%= link_to truncate_u(q.title, 15), news_path(q) %>
            </a>
          </h5>
      <% end %>
    </div>
    <div class="clear"></div>
  </div>
</section>
</body>
<%= render "comment/footer" %>